export const publications = [
  // 2025
  {
    authors: ["Sogodok Y.", "Pierson C."],
    year: 2025,
    title: "A review of current recommendations for lighting in buildings for optimal non-visual responses of occupants",
    venue: "IES Annual Conference, Anaheim (CA), USA, Aug. 21-23, 2025",
    volume: null, pages: null, doi: null, url: null, type: "conference", links: [],
  },
  {
    authors: ["Vali K.", "Au-Yeung W.-T.", "Kaye J.", "Pierson C."],
    year: 2025,
    title: "Light exposure of older adults living alone: a pilot study",
    venue: "CIE Midterm Meeting, Vienna, Austria, July 4-11, 2025",
    volume: null, pages: null, doi: null, url: null, type: "conference", links: [],
  },
  {
    authors: ["Orman A.", "Safranek S.", "Pierson C."],
    year: 2025,
    title: "Evaluation of spectral light simulation tools for prediction of ipRGC-influenced light responses in real-world offices with electrochromic glazing",
    venue: "Journal of Building Performance Simulation",
    volume: null, pages: "1-20", doi: "10.1080/19401493.2025.2515123", url: null, type: "journal", links: [],
  },
  {
    authors: ["Knoop M.", "Balakrishnan P.", "Blaszczak U.", "Diakite-Kortlever A.", "Dumortier D.", "Hernandez-Andres J.", "Inanici M.", "Kenny P.", "Maskarenj M.", "O'Mahoney P.", "Pierson C.", "Rudawski F.", "Thorseth A."],
    year: 2025,
    title: "Methodology to modify and adapt the standardised spectral power distributions for daylight to account for geographical, seasonal and diurnal variations for practical applications",
    venue: "Lighting Research & Technology",
    volume: null, pages: null, doi: "10.1177/14771535251322386", url: null, type: "journal", links: [],
  },
  {
    authors: ["Ko W. H.", "Suk J. Y.", "Pierson C.", "Pokhrel B."],
    year: 2025,
    title: "Estimating the visual and non-visual effects of window views through field data collection",
    venue: "ARCC 2025 International Conference, College Park (MD), USA, April 2-5, 2025",
    volume: null, pages: null, doi: null, url: null, type: "conference", links: [],
  },
  {
    authors: ["Knoop M.", "Balakrishnan P.", "Bellia L.", "Blaszczak U.", "Diakite-Kortlever A.", "Dumortier D.", "Hernandez-Andres J.", "Inanici M.", "Kenny P.", "Kobav M. B.", "Liang S.", "Luo T.", "Maskarenj M.", "O'Mahoney P.", "Pierson C.", "Thorseth A.", "Xue P."],
    year: 2025,
    title: "Our skies are too grey: Where is the colour?",
    venue: "Lighting Research & Technology",
    volume: null, pages: null, doi: "10.1177/14771535251322618", url: null, type: "journal", links: [],
  },
  // 2024
  {
    authors: ["Orman A.", "Pierson C."],
    year: 2024,
    title: "Accuracy of spectral simulation tools in field conditions",
    venue: "IES Annual Conference, New York City (NY), USA, Aug. 15-17, 2024",
    volume: null, pages: null, doi: null, url: null, type: "conference", links: [],
  },
  {
    authors: ["Pierson C."],
    year: 2024,
    title: "Teaching daylighting design through experiential learning",
    venue: "IES Annual Conference, New York City (NY), USA, Aug. 15-17, 2024",
    volume: null, pages: null, doi: null, url: null, type: "conference", links: [],
  },
  {
    authors: ["Pierson C."],
    year: 2024,
    title: "Experiencing Window Views",
    venue: "2024 SBSE Retreat, Oracle (AZ), USA, July 9-12, 2024",
    volume: null, pages: null, doi: null, url: null, type: "conference", links: [],
  },
  // 2023
  {
    authors: ["Quek G.", "Jain S.", "Karmann C.", "Pierson C.", "Wienold J.", "Andersen M."],
    year: 2023,
    title: "Comparison of questionnaire items for discomfort glare studies in daylit spaces",
    venue: "Lighting Research & Technology",
    volume: "55(7-8)", pages: "730-758", doi: "10.1177/14771535231203564", url: null, type: "journal",
    links: [{ label: "Paper available on Infoscience", url: "https://infoscience.epfl.ch/record/306185" }],
  },
  {
    authors: ["Orman A.", "Safranek S.", "Pierson C."],
    year: 2023,
    title: "Implementation of a reconstructed spectral sky definition in a light simulation tool and comparison to measurements",
    venue: "CIE Quadrennial Session, Ljubljana, Slovenia, Sep. 18-20, 2023",
    volume: null, pages: null, doi: null, url: null, type: "conference", links: [],
  },
  {
    authors: ["Karmann C.", "Pierson C.", "Danell M.", "Wienold J.", "Barthelemes V.", "Khovaly D.", "Andersen M."],
    year: 2023,
    title: "Variation in photopic and melanopic lighting in Swiss offices: a field study",
    venue: "CIE Quadrennial Session, Ljubljana, Slovenia, Sep. 18-20, 2023",
    volume: null, pages: null, doi: null, url: null, type: "conference", links: [],
  },
  {
    authors: ["Balakrishnan P.", "Diakite-Kortlever A.", "Dumortier D.", "Hernandez-Andres J.", "Kenny P.", "Maskarenj M.", "Pierson C.", "Thorseth A.", "Xue P.", "Knoop M."],
    year: 2023,
    title: "SkySpectra: an opensource data package of worldwide spectral daylight",
    venue: "CIE Quadrennial Session, Ljubljana, Slovenia, Sep. 18-20, 2023",
    volume: null, pages: null, doi: null, url: null, type: "conference", links: [],
  },
  // 2022
  {
    authors: ["Pierson C.", "Aarts M.", "Andersen M."],
    year: 2022,
    title: "Validation of spectral simulation tools in the context of ipRGC-influenced light responses of building occupants",
    venue: "Journal of Building Performance Simulation",
    volume: "16(2)", pages: "179-197", doi: "10.1080/19401493.2022.2125582", url: null, type: "journal", links: [],
  },
  {
    authors: ["Ko W. H.", "Schiavon S.", "et al."],
    year: 2022,
    title: "Window View Quality: Why It Matters and What We Should Do",
    venue: "LEUKOS",
    volume: "18:3", pages: "259-267", doi: "10.1080/15502724.2022.2055428", url: null, type: "journal", links: [],
  },
  {
    authors: ["Gkaintatzi-Masouti M.", "Pierson C.", "Van Duijnhoven J.", "Andersen M.", "Aarts M."],
    year: 2022,
    title: "A simulation tool for building and lighting design considering ipRGC-influenced light responses",
    venue: "BuildSim Nordic, Copenhagen, Denmark, Aug. 22-23, 2022",
    volume: null, pages: null, doi: null, url: null, type: "conference", links: [],
  },
  {
    authors: ["Pierson C.", "Gkaintatzi-Masouti M."],
    year: 2022,
    title: "Lark 2.0 -- a simulation tool to support the design of healthy indoor environments",
    venue: "IES Annual Conference, New Orleans, US, Aug. 18-20, 2022",
    volume: null, pages: null, doi: null, url: null, type: "conference", links: [],
  },
  {
    authors: ["Pierson C."],
    year: 2022,
    title: "Validation of Spectral Light Simulation Tools: Dataset of Simulated and Measured Indoor Light Exposure",
    venue: "Zenodo",
    volume: null, pages: null, doi: "10.5281/zenodo.5919054", url: null, type: "dataset", links: [],
  },
  // 2021
  {
    authors: ["Pierson C.", "Gkaintatzi-Masouti M.", "Aarts M.", "Andersen M."],
    year: 2021,
    title: "Validation of Spectral Simulation Tools for the Prediction of Indoor Electric Light Exposure",
    venue: "CIE Midterm Session, Online, Sep. 27-29, 2021",
    volume: null, pages: null, doi: "10.25039/x48.2021.OP05", url: null, type: "conference",
    links: [{ label: "Paper available on Infoscience", url: "https://infoscience.epfl.ch/record/291397" }],
  },
  {
    authors: ["Pierson C.", "Soto Magan V.", "Aarts M.", "Andersen M."],
    year: 2021,
    title: "A Conceptual Simulation Workflow to Guide Design Decisions Regarding the Effects of Daylight on Occupants' Alertness",
    venue: "Journal of Physics: Conference Series 2042, CISBAT 2021",
    volume: null, pages: null, doi: "10.1088/1742-6596/2042/1/012116", url: null, type: "journal", links: [],
  },
  {
    authors: ["Pierson C.", "Aarts M.", "Andersen M."],
    year: 2021,
    title: "Validation of Spectral Simulation Tools for the Prediction of Indoor Daylight Exposure",
    venue: "Building Simulation 2021, Bruges, Belgium, September 1-3, 2021",
    volume: null, pages: null, doi: null, url: null, type: "conference",
    links: [{ label: "Paper available on Infoscience", url: "https://infoscience.epfl.ch/record/291396" }],
  },
  {
    // Pierson C., Piderit B., Iwata T., Bodart M., Wienold J. (2021). Is There a Difference in how People from Different Socio-Environmental Contexts Perceive Discomfort Due to Glare from Daylight? Lighting Research & Technology. DOI:10.1177/1477153520983530
    authors: ["Pierson C.", "Piderit M.B.", "Iwata T.", "Bodart M.", "Wienold J."],
    year: 2021,
    title: "Is There a Difference in how People from Different Socio-Environmental Contexts Perceive Discomfort Due to Glare from Daylight?",
    venue: "Lighting Research & Technology",
    volume: null, pages: null, doi: "10.1177/1477153520983530", url: null, type: "journal", links: [],
  },
  // 2020
  {
    authors: ["Andersen M.", "Soto Magan V.", "Webler F.", "Pierson C."],
    year: 2020,
    title: "Light Hygiene in the Built Environment",
    venue: "ANFA International Conference, Online, September 14-25, 2020",
    volume: null, pages: null, doi: null, url: null, type: "conference",
    links: [{ label: "Extended Abstract available on Infoscience", url: "https://infoscience.epfl.ch/record/282954" }],
  },
  {
    authors: ["Pierson C.", "Aarts M.", "Andersen M."],
    year: 2020,
    title: "Applicability of Spectral Simulation to Predict Non-Visual Response to Daylight",
    venue: "EuroTech Postdoc Workshop, Copenhagen, Denmark, March 9-11, 2020",
    volume: null, pages: null, doi: null, url: null, type: "conference", links: [],
  },
  {
    authors: ["Pierson C.", "Cauwerts C.", "Bodart M.", "Wienold J."],
    year: 2020,
    title: "Tutorial: Luminance Maps for Daylighting Studies from High Dynamic Range Photography",
    venue: "LEUKOS",
    volume: "14(3)", pages: "111-148", doi: "10.1080/15502724.2019.1684319", url: null, type: "journal", links: [],
  },
  // 2019
  {
    authors: ["Pierson C."],
    year: 2019,
    title: "Discomfort glare perception from daylight: influence of the socio-environmental context",
    venue: "Universite catholique de Louvain (doctoral dissertation)",
    volume: null, pages: null, doi: null, url: null, type: "thesis", links: [{ label: "Thesis available on DIAL", url: "http://hdl.handle.net/2078.1/222924" }],
  },
  {
    authors: ["Pierson C.", "Wienold J.", "Bodart M."],
    year: 2019,
    title: "Is Daylight Glare Perceived Differently by People from Different Cultures?",
    venue: "VELUX Daylight Symposium, Paris, France, October 09-10, 2019",
    volume: null, pages: null, doi: null, url: null, type: "conference",
    links: [{ label: "Presentation available on YouTube", url: "https://www.youtube.com/watch?v=T6bmLisPsTo" }],
  },
  {
    authors: ["Wienold J.", "Iwata T.", "Sarey Khanie M.", "Erell E.", "Kraftan E.", "Rodriguez R.", "Yamin Garreton J.A.", "Tzempelikos T.", "Konstantzos I.", "Christoffersen J.", "Kuhn T.E.", "Pierson C.", "Andersen M."],
    year: 2019,
    title: "Cross-Validation and Robustness of Daylight Glare Metrics",
    venue: "Lighting Research & Technology",
    volume: "51(7)", pages: "983-1013", doi: "10.1177/1477153519826003", url: null, type: "journal", links: [],
  },
  {
    authors: ["Pierson C.", "Sarey Khanie M.", "Bodart M.", "Wienold J."],
    year: 2019,
    title: "Discomfort Glare Cut-Off Values from Field and Laboratory Studies",
    venue: "CIE Quadrennial Session, Washington D.C., USA, June 17-20, 2019",
    volume: null, pages: null, doi: null, url: null, type: "conference",
    links: [{ label: "Paper available on Infoscience", url: "https://infoscience.epfl.ch/record/274582" }],
  },
  // 2018
  {
    authors: ["Pierson C.", "Wienold J.", "Bodart M."],
    year: 2018,
    title: "Daylight Discomfort Glare Evaluation with Evalglare: Influence of Parameters and Methods on the Accuracy of Discomfort Glare Prediction",
    venue: "International Radiance Workshop, Loughborough, UK, Sept. 03-04, 2018",
    volume: null, pages: null, doi: null, url: null, type: "conference",
    links: [
      { label: "Workshops available on Radiance-Online", url: "https://www.radiance-online.org/community/workshops/2018-loughborough/" },
      { label: "Download presentation (PDF)", url: "https://www.radiance-online.org/community/workshops/2018-loughborough/presentations/25-EvalglareParameters.pdf" },
      { label: "Download recorded audio (MP3)", url: "https://www.radiance-online.org/community/workshops/2018-loughborough/audio/25-Clotilde_Pierson.mp3" },
    ],
  },
  {
    authors: ["Pierson C.", "Wienold J.", "Bodart M."],
    year: 2018,
    title: "Daylight Discomfort Glare Evaluation with Evalglare: Influence of Parameters and Methods on the Accuracy of Discomfort Glare Prediction",
    venue: "Buildings",
    volume: "8(8)", pages: "94", doi: "10.3390/buildings8080094", url: null, type: "journal", links: [],
  },
  {
    authors: ["Pierson C.", "Wienold J.", "Bodart M."],
    year: 2018,
    title: "Review of Factors Influencing Discomfort Glare Perception from Daylight",
    venue: "LEUKOS",
    volume: "14(3)", pages: "111-148", doi: "10.1080/15502724.2018.1428617", url: null, type: "journal",
    links: [{ label: "Accepted manuscript available on DIAL", url: "http://hdl.handle.net/2078.1/196098" }],
  },
  {
    authors: ["Pierson C."],
    year: 2018,
    title: "Discomfort Glare from Daylighting: Study of Factors Influencing Discomfort Glare Perception and Validation of a Universal Discomfort Glare Index",
    venue: "LumeNet, Copenhagen, Denmark, Aug. 16-17, 2018",
    volume: null, pages: null, doi: null, url: null, type: "conference", links: [],
  },
  {
    authors: ["Pierson C.", "Wienold J."],
    year: 2018,
    title: "High Dynamic Range Images Calibration for Luminance Maps Creation",
    venue: "CIE Expert Tutorial and Workshop on Research Methods for Human Factors in Lighting, Copenhagen, Denmark, Aug. 13-14, 2018",
    volume: null, pages: null, doi: null, url: null, type: "conference", links: [],
  },
  {
    authors: ["Pierson C.", "Wienold J.", "Altomonte S.", "Bodart M."],
    year: 2018,
    title: "Evaluation of Discomfort Glare through Glare Scales: What are we Really Measuring?",
    venue: "CIE Expert Tutorial and Workshop on Research Methods for Human Factors in Lighting, Copenhagen, Denmark, Aug. 13-14, 2018",
    volume: null, pages: null, doi: null, url: null, type: "conference", links: [],
  },
  // 2017
  {
    authors: ["Pierson C.", "Piderit M.B.", "Wienold J.", "Bodart M."],
    year: 2017,
    title: "Discomfort Glare from Daylighting: Influence of Culture on Discomfort Glare Perception",
    venue: "CIE Midterm Session, Jeju, South Korea, Oct. 20-28, 2017",
    volume: null, pages: null, doi: null, url: null, type: "conference",
    links: [{ label: "Paper available on Infoscience", url: "https://infoscience.epfl.ch/record/274581" }],
  },
  {
    authors: ["Pierson C.", "Wienold J.", "Bodart M."],
    year: 2017,
    title: "Discomfort Glare Perception in Daylighting: Influencing Factors",
    venue: "Energy Procedia",
    volume: "122", pages: "331-336", doi: "10.1016/j.egypro.2017.07.332", url: null, type: "journal", links: [],
  },
  {
    authors: ["Pierson C.", "Wienold J.", "Jacobs A.", "Bodart M."],
    year: 2017,
    title: "Luminance Maps from High Dynamic Range Imaging: Calibrations and Adjustments for Visual Comfort Assessment",
    venue: "LuxEuropa, Ljubljana, Slovenia, Sept. 18-20, 2017",
    volume: null, pages: null, doi: null, url: null, type: "conference",
    links: [{ label: "Paper available on Infoscience", url: "https://infoscience.epfl.ch/record/274400" }],
  },
  {
    authors: ["Pierson C.", "Cauwerts C.", "Wienold J.", "Bodart M."],
    year: 2017,
    title: "Discomfort Glare from Daylighting: Study of Factors Influencing Discomfort Glare Perception and Validation of a Universal Discomfort Glare Index",
    venue: "VELUX Daylight Symposium, Berlin, Germany, May 02-04, 2017",
    volume: null, pages: null, doi: null, url: null, type: "conference",
    links: [{ label: "Poster available on DIAL", url: "http://hdl.handle.net/2078.1/184657" }],
  },
  // 2016
  {
    authors: ["Pierson C.", "Bodart M."],
    year: 2016,
    title: "Validation and Universalization of Daylight Glare Probability Index",
    venue: "LumeNet, Ghent, Belgium, Apr. 07-08, 2016",
    volume: null, pages: null, doi: null, url: null, type: "conference", links: [],
  },
  // 2015
  {
    authors: ["Pierson C.", "Evrard A."],
    year: 2015,
    title: "Optimization of Facade Wall Building Systems in Walloon Region",
    venue: "International PLEA Conference, Bologna, Italy, Sept. 9-11, 2015",
    volume: null, pages: null, doi: null, url: null, type: "conference",
    links: [{ label: "Paper available on DIAL", url: "http://hdl.handle.net/2078.1/168040" }],
  },
];

export const publicationYears = [
  ...new Set(publications.map((p) => p.year)),
].sort((a, b) => b - a);
